export default {
  ENV: D1_ENV,
  MEMBER_TOKEN: SKILLFLO_ACCESS_TOKEN,
  ACCESS_TOKEN: SKILLFLO_MEMBER_TOKEN,
  KOLLUS_URL: SKILLFLO_KOLLUS_URL,
  KOLLUS_CUSTOM_KEY: SKILLFLO_KOLLUS_CUSTOM_KEY,
  GTM_ID: SKILLFLO_GTM_ID,
  CHANNEL_TALK_KEY: SKILLFLO_CHANNEL_TALK_KEY,
  DATADOG_CLIENT_TOKEN: SKILLFLO_DATADOG_CLIENT_TOKEN,
  DATADOG_APPLICATION_ID: SKILLFLO_DATADOG_APPLICATION_ID,
  BUILD_VERSION: SKILLFLO_BUILD_VERSION,
  ZOOM_CLIENT_ID: SKILLFLO_ZOOM_CLIENT_ID,
  ZOOM_CLIENT_SECRET: SKILLFLO_ZOOM_CLIENT_SECRET,
};
